### PR TITLE
Implemented update method on most JSONPath descendents. Tests included.

### PR DESCRIPTION
**Pull request by joshbenner**
Mostly addresses #21. I didn't add update() implementations for Parent, Union, or Intersect, as I wasn't sure it made sense to do so. More esoteric test cases might be good, too, as I'm not 100% sure the implementations work as expected at all times.

### CODE REVIEW

**Comment by mgcdanny** [comment]
Is there a reason why this hasn't been merged in to the master branch?

**Comment by mgcdanny** [comment]
@joshbenner 
Either I am doing something wrong or I found a bug with this pull request.  Check out this example:

```python
from jsonpath_rw import parse
jsonpath_expr = parse('$..baz')
data = {'foo': [{'baz': 1}, {'baz': 2}]}
data_copy = data.copy()
jsonpath_expr.update(data, '1234')
assert data_copy == {'foo': [{'baz': 1234}, {'baz': 1234}]}
```

**Comment by kennknowles** [comment]
At a high level, I'd kind of like to reserve the word `update` for creating a copy with new values in certain places, and call this `set`, but I like this. It was even my original intent with the library, but I got too busy. I will be happy with whatever name is more Pythonic.

**Comment by kennknowles** [comment]
More tests, such as those with lists within dictionaries and vice versa, would be nice.

**Comment by PositiveAlex** [comment]
I believe it is very handy PR, can anyone tell me what is needed to merge it?

**Comment by jonathanglima** [comment]
+1

this will also update passing lambdas instead of the value? if not, that's a great enhancement

**Comment by PositiveAlex** [comment]
Should we believe this PR could be aprooved?

**Comment by carpnick** [comment]
+1

**Comment by jimmycliff** [comment]
+1.   Useful feature.

**Comment by carlosmmelo** [comment]
+1

**Comment by quazar0** [comment]
Thanks for this update.  BTW, does this allow removal of a selected element?

**Comment by shuaiyuancn** [comment]
I'm seeing `NotImplementedError`:

```
from jsonpath_rw.parser import parse
parse('$.a').update({'a': 1}, 2)
```

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-59-940582069d38> in <module>()
      1 from jsonpath_rw.parser import parse
----> 2 parse('$.a').update({'a': 1}, 2)

/databricks/python/local/lib/python2.7/site-packages/jsonpath_rw/jsonpath.pyc in update(self, data, val)
     28     def update(self, data, val):
     29         "Returns `data` with the specified path replaced by `val`"
---> 30         raise NotImplementedError()
     31 
     32     def child(self, child):

NotImplementedError: 
```

**Comment by GusBricker** [comment]
The reason you are getting the NotImplementedError is because the current version (1.4.0) on PyPi predates this pull request.

**Comment by namratha-bharadwaj** [comment]
Hello... I see the "raise NotImplementedError(), NotImplementedError" when I tried using the update method to change json elements. Is there a work-around for this?

**Comment by srhopkins** [comment]
Is there going to be a new release cut with `update` feature?

**Comment by srhopkins** [comment]
Are the plans to cut a new release soon with  the `update` feature?

**Comment by kennknowles** [comment]
It has been so long since I did a pypi release I don't remember how ;_;

**Pull request merged**
