### PR TITLE
Deprecation of repo

### PR DESCRIPTION
**Pull request by ailjushkin**

### CODE REVIEW

**Comment by ailjushkin** [comment]
@kennknowles I should also fix a travis build in this PR. Reason: Travis CI does not have 3.2, 3.3 version of python anymore to test on.
https://docs.travis-ci.com/user/languages/python/#python-versions

**Comment by ailjushkin** [comment]
@kennknowles I noticed how many donloads per month has this package.
image
Thats huge. What do you think about all that?

**Comment by kennknowles** [comment]
Good point. Why don't we merge into the more popular repo and publish to the most popular package name too. I'm happy to give write access to build up the maintainers of this. I wonder if it would make sense to put it in one of the lighter weight OSS foundations (if we maintain it for a while without collecting CLAs it will make it hard to get into a foundation).

**Comment by ailjushkin** [comment]
Yeah sure. I'll try to contact users who forks it and ask them if they want to get full access to the main repo

**Pull request closed without merging**
